name: test acton
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: cache nix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build
